# Generated by Django 4.0.3 on 2022-03-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_content_comment_alter_comment_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
